---
title: "ALL CALVES"
author: "WAK"
format: html
editor: visual
---

```{r}
#| include: false
#| warning: false
#| echo: false

library(epiDisplay)
library(knitr)
library(pROC)
library(tidyverse)
library(readxl)
library(ggplot2)
library(gmodels)
library(ggbeeswarm)
library(dplyr)
library(readr)
library(ggpubr)
library(psych)
library(lme4)
library(Matrix)
library(lmerTest)
library(irr)
library(lmerTest)
library(emmeans)
library(doBy)       
library(gmodels)    
library(car)           
library(cowplot)       
library(gridGraphics)  
library(multcomp)
library(hms)
library(gt)
library(lubridate)
library(nlme)
library(extrafont)
library(stringi)
library(survival)
library(survminer)
```

### Data Steps

#### Pull in data

```{r}
#| include: false
#| warning: false
#| echo: false

all <- read_csv('data/all enroll MOC.csv')

all %>%
  group_by(ID) %>%
  summarize(n = n()) %>%
  filter(n > 1)

stack <- read_csv('data/clean.csv')


full <- all %>% 
  left_join(stack, by = "ID")

write.csv(x = full, file = "data/full.csv")


```

#### Creating new variables

```{r}
#| warning: false
#| echo: false

#first select which variables remain in the data set: 

full_new <- 
  full %>% 
  select( ID, EID.x, BIRTH, sex, BREED,Breed2, BRTHW, SERUM, SORCE, TRL2, LOADT, Date_PNEU1, Remark_PNEU1, Date_PNEU2, Remark_PNEU2, Date_PNEU3, Remark_PNEU3, Date_SCOURS1, Remark_SCOURS1, Date_SCOURS2, Remark_SCOURS2, Date_BLOAT1, Remark_BLOAT1, Date_BLOAT2, Remark_BLOAT2, Date_DIED1, Remark_DIED1)

full_new$TRL2 = as.character(full_new$TRL2)


#convert all dates into date vs. chr variables

head(full_new$BIRTH)
head(full_new$LOADT)


#create a new variable called ARR wich is LOADT + 1
full_new <- full_new %>%
  mutate(
    LOADT_date = mdy(LOADT),          
    ARR = LOADT_date + days(1)
  )

#convert dates so can add and subtract

full_new <- full_new %>%
  mutate(
    BIRTH = mdy(BIRTH),
    LOADT = mdy(LOADT))

#create some new variables realted to days in age at stuff and age from arrival at stuff. 

#days in age load
#days in age arrival
#dfa pneu1
#dfa pneu2
#dfa pneu3
#dfa scour1
#dfa scour 2
#dfa bloat1
#dfa bloat2
#dfa died

full_new<- 
  full_new %>% 
  mutate(
    diaload = as.numeric(LOADT - BIRTH), 
    diaARR = as.numeric (ARR - BIRTH), 
    dfaP1 = as.numeric(Date_PNEU1 - ARR),
    dbtwP12 = as.numeric(Date_PNEU2-Date_PNEU1),
    dbtwP23 = as.numeric(Date_PNEU3-Date_PNEU2),
    dfaP2 = as.numeric(Date_PNEU2 - ARR), 
    dfaP3 = as.numeric(Date_PNEU3 - ARR), 
    dfaD1 = as.numeric(Date_SCOURS1 - ARR),
    dfaD2 = as.numeric(Date_SCOURS2 - ARR), 
    dbtwD12 = as.numeric(Date_SCOURS2 - Date_SCOURS1),
    dfaB1 = as.numeric(Date_BLOAT1 - ARR), 
    dfaB2 = as.numeric(Date_BLOAT2 - ARR), 
    dfaDIED = as.numeric(Date_DIED1 - ARR))

#create unique identifier for trailer load using date and trl2 

full_new <- full_new %>%
  mutate(
    LOAD = factor(paste(LOADT, TRL2, Breed2, sep = "_")))

datachecks <- full_new %>% 
  count(LOAD)

datachecks

write.csv(x = datachecks, file = "data/trailer loads.csv")

#n=4 calves that died/euthanized at MOC before they left but were still enrolled. Removed them from data sheet; also removed 1 animal that was loaded out on 8.11 for unknown reasons (the only animal that day)

#need to check with Brett on the trailer load data, looks like there are ~16ish loads for each SD, which is btw 2000-3000 calves per group.

#got the trailer loads figured out! Now need to pull in the data to merge on LOAD so can remove data that don't need (~10,000 calves)

load <- read_csv('data/Trailer Load FINAL.csv')

load %>% 
  summarize(
    sum = sum(n))



full_new1 <-  full_new %>% 
  inner_join(load, by = "LOAD")



```

#### Messing around with Pneu/Scour

```{r}
#| warning: false
#| echo: false

#add some new variables like pn1yn etc for all treatments but need to use days between for PN1/2/3

full_new1<- full_new1 %>% 
  mutate(
   PN1a = if_else(dfaP1>=0, 1, 0) %>% replace_na(0), 
   PN2 = if_else(dfaP2>=0, 1, 0)%>% replace_na(0),
   PN3 = if_else(dfaP3>=0, 1, 0) %>% replace_na(0), 
   DIA1 = ifelse(dfaD1>=0, 1, 0)%>% replace_na(0), 
   DIA2 = ifelse(dfaD2>=0, 1, 0)%>% replace_na(0), 
   B1 = ifelse(dfaB1>=0, 1, 0)%>% replace_na(0), 
   B2 = ifelse(dfaB2>=0, 1, 0)%>% replace_na(0), 
   DIED = ifelse(dfaDIED>=0, 1, 0)%>% replace_na(0))

#add some new variables like pn1yn etc for all treatments but need to use days between for PN1/2/3
##WORKING ON THIS NEED TO MAKE IT AND/OR statement I think? 
#new resp event if >7d from previous treatment

#the n doesn't change of total treatment events if use 7 or 5d. Wonder what happens if use 14d? 


FINAL7_new<- full_new1 %>% 
  mutate(
    PN2a = case_when(
      PN2 == 1 & dbtwP12 >= 7 | PN3 == 1 & dbtwP23 >= 7    ~ 1, 
      PN2 == 1 & dbtwP12 <  7 | PN2 == 0  | PN3 == 1 & dbtwP23 < 7 ~ 0))


FINAL7_new<- FINAL7_new %>% 
  mutate(
    Date_PN1a = Date_PNEU1)

FINAL7_new <- FINAL7_new %>% 
  mutate(
    Date_PN2a = case_when(
      PN2a == 1 & dbtwP12 <7 ~ FINAL7_new$Date_PNEU3, 
      PN2a == 1 & dbtwP12 >= 7 ~ FINAL7_new$Date_PNEU2))



FINAL14_new<- full_new1 %>% 
  mutate(
    PN2a = case_when(
      PN2 == 1 & dbtwP12 >= 14 | PN3 == 1 & dbtwP23 >= 14    ~ 1, 
      PN2 == 1 & dbtwP12 <  14 | PN2 == 0  | PN3 == 1 & dbtwP23 < 14 ~ 0))



FINAL14_new<- FINAL14_new %>% 
  mutate(
    Date_PN1a = Date_PNEU1)

FINAL14_new <- FINAL14_new %>% 
  mutate(
    Date_PN2a = case_when(
      PN2a == 1 & dbtwP12 <14 ~ FINAL14_new$Date_PNEU3, 
      PN2a == 1 & dbtwP12 >= 14 ~ FINAL14_new$Date_PNEU2))


FINAL7_new %>% 
  summarize(
    sum(PN1a), 
    sum(PN2a), 
    sum(DIA1))

FINAL14_new %>% 
  summarize(
    sum(PN1a), 
    sum(PN2a))

FINAL7_new %>% 
  group_by(Remark_PNEU1) %>% 
  count()

FINAL7_new %>% 
  group_by(Remark_PNEU2) %>% 
  count()


write.csv(x = FINAL7_new, file = "data/PNchecks.csv")

#PN1 and PN2 are now correct! Yay!
   


#SCOURS
#now need to figure out the calves who had scours treatment prior to shipment (what were they treated with?) and likely need to exlcude them (n=420 total calves; 4% of data) and control for them when evaluating PN?


FINAL7_new %>% 
  filter(dfaD1<0) %>% 
 # group_by(Remark_SCOURS1) %>% 
  count()

FINAL7_new %>% 
  filter(dfaD1<0) %>% 
  group_by(SD) %>% 
  count()

FINAL7_new %>% 
  group_by(SD) %>% 
  count()


#make new dfaPN1a and dfaPN2a

FINAL7_new<- 
  FINAL7_new %>% 
  mutate(
    dfaPN1a = as.numeric(Date_PN1a - ARR), 
    dfaPN2a = as.numeric (Date_PN2a - ARR))

#new variable to say if calves were treated prior to departure for DIA (4% of calves, same in all groups)

FINAL7_new <- FINAL7_new %>% 
  mutate(
    diaex = 
      case_when(is.na(dfaD1) ~ 0,
                dfaD1<0 ~  1, 
                dfaD1>= 0 ~ 0))

FINAL7_new %>% 
  summarize(
    sum = sum(diaex, na.rm=TRUE))

#serum total protein, messing with

FINAL7_new <-FINAL7_new %>% 
  mutate(
    stp = SERUM/10)


```

### Descriptive Analysis

#### General Description

This description is for all calves with a TRL2 item (n=10324)

```{r}
#| warning: false
#| echo: false



FINAL7_new %>% 
  group_by(SD) %>% 
  summarize (Count = n())

FINAL7_new |> 
  group_by(SD, Sex) |> 
  summarize (Count = n())

FINAL7_new |> 
  group_by(sbTRT) |> 
  summarize (Count = n())

FINAL7_new %>% 
  group_by(SORCE) %>% 
  summarize (Count = n())


FINAL7_new |> 
  group_by(SD) |> 
  summarize (
    bwt = mean(BRTHW), 
    bwtsd = sd(BRTHW),
    arrage = mean(diaARR), 
    arrA   = sd (diaARR), 
    loadage = mean(diaload), 
    sdload  = sd (diaload))

FINAL7_new |>
  filter(stp > 0) |>
  group_by(SD) |>
  summarize(
    count = n(),
    mean_stp = mean(stp, na.rm = TRUE),
    sd_stp   = sd(stp, na.rm = TRUE),
    .groups = "drop")

FINAL7_new |> 
  filter(stp!=0) %>% 
  ggplot(mapping=aes(x=stp))+
  theme_classic()+
  geom_histogram(binwidth=0.2, 
                 fill="skyblue", 
                 color="black", 
                 alpha=0.7)+
  labs(title = "Histogram of stp")


FINAL7_new |> 
  group_by(SD, DB) |> 
  summarize (
    bwt = mean(BRTHW), 
    bwtsd = sd(BRTHW),
    arrage = mean(diaARR), 
    arrA   = sd (diaARR),
    loadage = mean(diaload), 
    sdload  = sd (diaload))

FINAL7_new |>
  filter(stp > 0) |>
  group_by(SD, DB) |>
  summarize(
    count = n(),
    mean_stp = mean(stp, na.rm = TRUE),
    sd_stp   = sd(stp, na.rm = TRUE),
    .groups = "drop")


FINAL7_new %>% 
  group_by(SD) %>% 
  summarize(
    prop_P1 = mean(PN1a, na.rm=TRUE),
    prop_P2 = mean(PN2a, na.rm=TRUE),
    meandfaP1 = mean(dfaPN1a, na.rm = TRUE), 
    meandfaP2 = mean(dfaPN2a, na.rm = TRUE),
    prop_DED = mean(DIED), 
    avg_DED = mean(dfaDIED, na.rm=TRUE))


FINAL7_new %>% 
  group_by(SD, DBxS) %>% 
  summarize(
    prop_P1 = mean(PN1a, na.rm=TRUE),
    prop_P2 = mean(PN2a, na.rm=TRUE),
    meandfaP1 = mean(dfaPN1a, na.rm = TRUE), 
    meandfaP2 = mean(dfaPN2a, na.rm = TRUE),
    prop_DED = mean(DIED), 
    avg_DED = mean(dfaDIED, na.rm=TRUE))

FINAL7_new %>% 
  filter (diaex == 0) %>% 
  group_by(SD) %>% 
  summarize(
    prop_DIA = mean(DIA1, na.rm=TRUE), 
    meandfaD1 = mean(dfaD1, na.rm=TRUE))


FINAL7_new %>% 
  filter (diaex == 0) %>% 
  group_by(SD, DB) %>% 
  summarize(
    prop_DIA = mean(DIA1, na.rm=TRUE), 
    meandfaD1 = mean(dfaD1, na.rm=TRUE))


FINAL7_new %>% 
  filter (diaex == 1) %>% 
  group_by(SD) %>% 
  summarize(
    prop_DIA = mean(DIA1, na.rm=TRUE), 
    meandfaD1 = mean(dfaD1, na.rm=TRUE), 
     prop_P1 = mean(PN1a, na.rm=TRUE))


FINAL7_new %>% 
  filter (diaex == 1) %>% 
  group_by(SD, DB) %>% 
  summarize(
    prop_DIA = sum(diaex, na.rm=TRUE), 
    meandfaD1 = mean(dfaD1, na.rm=TRUE))




```

#### Load summaries

```{r}
#| warning: false
#| echo: false



load %>% 
  group_by(SD) %>% 
  summarize (Count = n(), 
             total = sum(n), 
             mean = mean(n),
             sd   = sd(n))

load %>% 
  group_by(SD, DBxS) %>% 
  summarize (Count = n(), 
             total = sum(n), 
             mean = mean(n),
             sd   = sd(n))

```

#### Health Treatment to 60d

```{r}
#| warning: false
#| echo: false


#need to right censor data to 30 and 60d (?) and clean up the data set becasue there's too many variables. 


#create new variables DIA30; PNEU30, PNEU60 such that if the calf has a treatment and is less than the prescribed days, then the day is dfaPN1a but otherwise, it's 30 or 60 to allow sensoring. 


FINAL7_new <- FINAL7_new %>% 
  mutate(
    DIA30 = if_else(diaex == 0,
                    coalesce(dfaD1, 30),
                    NA_real_))


FINAL7_new <- FINAL7_new %>% 
  mutate(
    D30 = if_else(DIA30 < 30, 1L, 0L))



FINAL7_new <- FINAL7_new %>% 
  mutate(
    PNEU30 = pmin(dfaPN1a, 30, na.rm = TRUE))

FINAL7_new <- FINAL7_new %>% 
  mutate(
    P30 = if_else(PNEU30 < 30, 1L, 0L))


FINAL7_new <- FINAL7_new %>% 
  mutate(
    PNEU60 = pmin(dfaPN1a, 60, na.rm = TRUE))

FINAL7_new <- FINAL7_new %>% 
  mutate(
    P60 = if_else(PNEU60 < 60, 1L, 0L))


#mortality

FINAL7_new <- FINAL7_new %>% 
  mutate(
    DED30 = pmin(dfaDIED, 30, na.rm = TRUE))

FINAL7_new <- FINAL7_new %>% 
  mutate(
    D30yn = if_else(DED30 < 30, 1L, 0L))


FINAL7_new <- FINAL7_new %>% 
  mutate(
    DED60 = pmin(dfaDIED, 60, na.rm = TRUE))

FINAL7_new <- FINAL7_new %>% 
  mutate(
    D60yn = if_else(DED60 < 60, 1L, 0L))



#now clean up the data set!

FINAL_Analysis <- FINAL7_new %>% 
  select(ID, sex, Breed2, stp, BRTHW, SORCE, SD, DB, diaload, diaARR, PN1a, PN2a, DIA1, D30, P30, P60, D30yn, D60yn, diaex, DIA30, PNEU30, PNEU60, DED30, DED60, Remark_PNEU1, Remark_DIED1)

FINAL_Analysis <- FINAL_Analysis %>%
  mutate(SD_DB = paste(SD, DB, sep = "_"))
  

#Scours

FINAL_Analysis %>% 
  filter(diaex == 0) %>% 
  group_by(SD) %>% 
  summarize(
    count = n(),
    prop_DIA = mean(DIA1, na.rm=TRUE), 
    sum_DIA  = sum(DIA1, na.rm=TRUE))

FINAL_Analysis %>% 
  filter(diaex == 0) %>% 
  group_by(SD, DB) %>% 
  summarize(
    count = n(),
    prop_DIA = mean(DIA1, na.rm=TRUE), 
    sum_DIA  = sum(DIA1, na.rm=TRUE))


FINAL_Analysis %>% 
  filter(diaex == 0) %>% 
  group_by(SD, DIA1) %>% 
  summarize(
    dfa_mean = mean(DIA30),
    dfa_sd   = sd(DIA30))



#PNEU30


FINAL_Analysis %>% 
  group_by(SD) %>% 
  summarize(
    count = n(),
    prop_PN1 = mean(P30, na.rm=TRUE), 
    sum_PN1  = sum(P30, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, DB) %>% 
  summarize(
    count = n(),
    prop_PN1 = mean(P30, na.rm=TRUE), 
    sum_PN1  = sum(P30, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, PN1a) %>% 
  summarize(
    dfa_mean = mean(PNEU30),
    dfa_sd   = sd(PNEU30))

FINAL_Analysis %>% 
  filter(P60 == 1) %>% 
  group_by(Remark_PNEU1, DB) %>% 
  summarize(
    count = n())


#PNEU 60d
FINAL_Analysis %>% 
  group_by(SD) %>% 
  summarize(
    count = n(),
    prop_PN1 = mean(P60, na.rm=TRUE), 
    sum_PN1  = sum(P60, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, DB) %>% 
  summarize(
    count = n(),
    prop_PN1 = mean(P60, na.rm=TRUE), 
    sum_PN1  = sum(P60, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, PN1a) %>% 
  summarize(
    dfa_mean = mean(PNEU60),
    dfa_sd   = sd(PNEU60))

#MORTALITY
#30d mortality

FINAL_Analysis %>% 
  group_by(SD) %>% 
  summarize(
    count = n(),
    prop_DED1 = mean(D30yn, na.rm=TRUE), 
    sum_DED1  = sum(D30yn, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, DB) %>% 
  summarize(
    count = n(),
    prop_DED1 = mean(D30yn, na.rm=TRUE), 
    sum_DED1  = sum(D30yn, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, D30yn) %>% 
  summarize(
    dfa_mean = mean(DED30),
    dfa_sd   = sd(DED30))

FINAL_Analysis %>% 
  filter(D60yn == 1) %>% 
  group_by(Remark_DIED1) %>% 
  summarize(
    count = n())


#DEAD 60d
FINAL_Analysis %>% 
  group_by(SD) %>% 
  summarize(
    count = n(),
    prop_DED1 = mean(D60yn, na.rm=TRUE), 
    sum_DED1  = sum(D60yn, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, DB) %>% 
  summarize(
    count = n(),
    prop_DED1 = mean(D60yn, na.rm=TRUE), 
    sum_DED1  = sum(D60yn, na.rm=TRUE))

FINAL_Analysis %>% 
  group_by(SD, D60yn) %>% 
  summarize(
    dfa_mean = mean(DED60),
    dfa_sd   = sd(DED60))


```

### KM Curves for Morbidity and Mortality

#### Scours 30d

```{r}



#scours to 30d. 
FINAL_Analysis_filt <- FINAL_Analysis %>% 
  filter(diaex != 1)

surv_obj <- Surv(
  time  = FINAL_Analysis_filt$DIA30,
  event = FINAL_Analysis_filt$D30)

fit <- survfit(
  surv_obj ~ SD,
  data = FINAL_Analysis_filt)

ggsurvplot(
  fit,
  data = FINAL_Analysis_filt,
  pval = TRUE,
  pval.coord = c(5, 0.6),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Scours Treatment Survival Probability",
  xlim = c(0, 28),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D30)






#scours to 30d.DAIRY vs. BEEF 
FINAL_Analysis_filt <- FINAL_Analysis %>% 
  filter(diaex != 1)

surv_obj <- Surv(
  time  = FINAL_Analysis_filt$DIA30,
  event = FINAL_Analysis_filt$D30)

fit <- survfit(
  surv_obj ~ DB,
  data = FINAL_Analysis_filt)

ggsurvplot(
  fit,
  data = FINAL_Analysis_filt,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Scours Treatment Survival Probability",
  xlim = c(0, 28),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D30)

```

#### Resp 30d

```{r}


#resp to 30d. 

surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU30,
  event = FINAL_Analysis$P30)

fit <- survfit(
  surv_obj ~ SD,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.8),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Resp Treatment Survival Probability",
  xlim = c(0, 28),
   ylim = c(0.75, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$P30)





#resp to 30d. DAIRY vs. BEEF

surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU30,
  event = FINAL_Analysis$P30)

fit <- survfit(
  surv_obj ~ DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
  break.time.by = 7
)


table(FINAL_Analysis_filt$P30)
```

#### Resp 60d

```{r}
#resp to 60d. 

surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU60,
  event = FINAL_Analysis$P60)

fit <- survfit(
  surv_obj ~ SD,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
   pval.coord = c(5, 0.8),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 60),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$P60)



#DAIRY VS BEEF IN THE THUNDERDOME

surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU60,
  event = FINAL_Analysis$P60)

fit <- survfit(
  surv_obj ~ DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 60),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$P60)
```

#### Death 30d

```{r}

#30d mortality 

surv_obj <- Surv(
  time  = FINAL_Analysis$DED30,
  event = FINAL_Analysis$D30yn)

fit <- survfit(
  surv_obj ~ SD,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.95),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
   ylim = c(0.9, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D30yn)


#30d mortality DAIRY VS. BEEFIES

surv_obj <- Surv(
  time  = FINAL_Analysis$DED30,
  event = FINAL_Analysis$D30yn)

fit <- survfit(
  surv_obj ~ DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D30yn)
```

#### Death 60d

```{r}

#60d mortality 

surv_obj <- Surv(
  time  = FINAL_Analysis$DED60,
  event = FINAL_Analysis$D60yn)

fit <- survfit(
  surv_obj ~ SD,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.95),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
     ylim = c(0.9, 1.0),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D60yn)

#DAIRY VS BEEF 

surv_obj <- Surv(
  time  = FINAL_Analysis$DED60,
  event = FINAL_Analysis$D60yn)

fit <- survfit(
  surv_obj ~ DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
  break.time.by = 7
)


table(FINAL_Analysis_filt$D60yn)
```

### KM Curves SDDB

#### Scours 30d

```{r}

FINAL_Analysis_filt <- FINAL_Analysis %>% 
  filter(diaex != 1)

surv_obj <- Surv(
  time  = FINAL_Analysis_filt$DIA30,
  event = FINAL_Analysis_filt$D30)

fit <- survfit(
  surv_obj ~ SD_DB,
  data = FINAL_Analysis_filt)

ggsurvplot(
  fit,
  data = FINAL_Analysis_filt,
  pval = TRUE,
  pval.coord = c(5, 0.6),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Scours Treatment Survival Probability",
  xlim = c(0, 28),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)

```

#### Resp 30d

```{r}


surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU30,
  event = FINAL_Analysis$P30)

fit <- survfit(
  surv_obj ~ SD_DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.8),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Resp Treatment Survival Probability",
  xlim = c(0, 28),
   ylim = c(0.75, 1.0),
  break.time.by = 7
)

```

#### Resp 60d

```{r}

surv_obj <- Surv(
  time  = FINAL_Analysis$PNEU60,
  event = FINAL_Analysis$P60)

fit <- survfit(
  surv_obj ~ SD_DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
   pval.coord = c(5, 0.8),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 60),
  ylim = c(0.5, 1.0),
  break.time.by = 7
)

```

#### Death 30d

```{r}
surv_obj <- Surv(
  time  = FINAL_Analysis$DED30,
  event = FINAL_Analysis$D30yn)

fit <- survfit(
  surv_obj ~ SD_DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.95),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
   ylim = c(0.9, 1.0),
  break.time.by = 7
)

```

#### Death 60d

```{r}

surv_obj <- Surv(
  time  = FINAL_Analysis$DED60,
  event = FINAL_Analysis$D60yn)

fit <- survfit(
  surv_obj ~ SD_DB,
  data = FINAL_Analysis)

ggsurvplot(
  fit,
  data = FINAL_Analysis,
  pval = TRUE,
  pval.coord = c(5, 0.95),
  conf.int = TRUE,
  risk.table = FALSE,
  xlab = "Time (days)",
  ylab = "Survival Probability",
  xlim = c(0, 28),
     ylim = c(0.9, 1.0),
  break.time.by = 7
)

```
