---
title: "IceCube SD 2025"
author: "WAK"
date: "today"
format: 
  html:
    toc: true 
    toc-float: true
    toc-location: left
---

```{r}
#| include: false
#| warning: false
#| echo: false

library(epiDisplay)
library(knitr)
library(pROC)
library(tidyverse)
library(readxl)
library(ggplot2)
library(gmodels)
library(ggbeeswarm)
library(dplyr)
library(readr)
library(ggpubr)
library(psych)
library(lme4)
library(Matrix)
library(lmerTest)
library(irr)
library(lmerTest)
library(emmeans)
library(doBy)       
library(gmodels)    
library(car)           
library(cowplot)       
library(gridGraphics)  
library(multcomp)
library(hms)
library(gt)
library(lubridate)
library(nlme)
library(extrafont)
```

## Data Steps

### Bring in Data

```{r}
#| include: false
#| warning: false
#| echo: false

lay <- read_csv('data/activity_report_1.csv')

new <- lay |>
 separate(Start, into = c("Date", "Time"), sep = " ")

unique(new$Date)
charToRaw(new$Date[1])
class(new$Date)

charToRaw(new$Time[1])

new$Date <- as.Date(as.character(new$Date), format = "%m/%d/%Y")
new$Time <- as_hms(paste0(new$Time, ":00"))


key<- read_csv("data/enroll.csv")

key<-key |> 
  mutate(Bdat=mdy(Bdat), 
         DatMOC=mdy(DatMOC), 
         DatON = mdy(DatON), 
         ToTCC = mdy(ToTCC), 
         ArrTCC = mdy(ArrTCC), 
         DatOFF = mdy(DatOFF))
```

### Merge Two Data Sets

```{r}
#| include: false
#| warning: false
#| echo: false


intersect(new$Cow, key$Cow)

combined <- new |> 
  inner_join(key, by = "Cow") %>% 
  filter(!Cow %in% c(216, 268))

#filtering out those two calves bc I can't match them on tfship as they have a loss of 1:15 to 2hrs of data around the time of shipping?

combinednew <- 
  combined |> 
  mutate(datetime = as.POSIXct(paste(Date, Time), format = "%Y-%m-%d %H:%M:%S"), 
         datetimeon = as.POSIXct(paste(DatON, TimeONp), format = "%Y-%m-%d %H:%M:%S"), 
         datetimeoff = as.POSIXct(paste (DatOFF, TimeOFFp), format = "%Y-%m-%d %H:%M:%S"))

#This filters to only times when IceCubes were on calves (128184obs to 124455obs)

use <- combinednew |> 
  filter(datetime >= datetimeon, datetime <= datetimeoff)
```

### Flagging to Trailer Entry

```{r}
#| include: false
#| warning: false
#| echo: false

#adds a variable called "match_flag" that flags when a calf was scanned to ship

use <- use |> 
  mutate(
    match_flag = if_else(
      Date == ToTCC & 
        (as.numeric(TimetoTCCp - Time, units="mins") >=0 &
        as.numeric(TimetoTCCp - Time, units = "mins") <= 14), 
      1,  
      0    )) 

#adds variable tfship, which scan to TCC time 0, all time before progressively negative, all time after progressively positive

use |> 
  group_by(Cow) |> 
  summarize(matches = list(which(match_flag == 1)))

use <- use |> 
  group_by(Cow) |>  
  mutate(
    tfship = if_else(match_flag == 1, 0, NA_integer_),  
    tfship = if_else(is.na(tfship), row_number() - which(match_flag == 1), tfship)  
  ) |> 
  ungroup()

#creates a new variable called hoursfrom which groups behaviors by hours from the second feeding. This will allow looking at the 8hrs prior to feeding and the 8 or 12 hrs later. Should probably make a new df to look at that. 

merged_data <- use |> 
  mutate(
    hoursfrom = case_when(
      tfship == 0 ~ 0,                                      
      tfship < 0 ~ as.integer((abs(tfship) - 1) %/% 4 + 1) * -1,  
      tfship > 0 ~ as.integer((tfship - 1) %/% 4 + 1)           
    )
  )



hour <- merged_data |> 
  group_by(Cow, hour = floor(hoursfrom)) |>  
  summarise(
    Lying = sum(`Lying Time`, na.rm = TRUE)/60,   
    Standing = sum(`Standing Time`, na.rm = TRUE)/60, 
    Steps = sum(Steps), 
    LB = sum(Transitions),
    MI = sum(`Motion Index`),
    FOO = first(FOO),              
    TRT = first(TRT),
    OneLoad = first(OneLoad),
    .groups = "drop")

hour$timecat <- cut(hour$hour, 
                breaks = c(-Inf, -1, 28, Inf), 
                labels = c("pre", "during", "post"))
    
  

fullcut<-
merged_data %>% 
  filter(tfship >= -96 & tfship <= 200) 

write.csv(x = fullcut, file = "data/fulldatachecks.csv")

#data set that is more balanced with only calves within 1 load (exclude the 3.0sq ft carry over calves)
oneload <-
  hour %>% 
  filter (!OneLoad == 0)
  
```

## Calf Summary - Who in data set?

```{r}
#| warning: false
#| echo: false


key |> 
  group_by(TRT) |> 
  summarize (Count = n())

key %>% 
  group_by(TRT, OneLoad) %>% 
  summarize (count = n())
 
key |> 
  group_by(Section) |> 
  summarize (Count = n())

key |> 
  group_by(TRT, FOO) |> 
  summarize(Count = n())

key |> 
  group_by(TRT, Section) |> 
  summarize (Count = n())


key |> 
  group_by(TRT) |> 
  summarize (Count = n(), 
             mean = mean(TimeTrip), 
             sd = sd(TimeTrip))

key$TRT <- relevel(factor(key$TRT), ref = "DF3.0")
lm_bw <- lm(TimeTrip ~ TRT, data=key)
summary(lm_bw)


  
  

```

## Data Investigation

```{r}


hour %>% 
  filter(hour >= -24 & hour <= 50) %>% 
  ggplot(aes(x=hour, y=Lying, color = factor(Cow), group = Cow))+
         geom_line (aes(fill = Cow), size = 1, alpha = 0.1)+
         geom_point()+ 
         theme_minimal()


hour %>% 
  filter(hour >= -24 & hour <= 50) %>% 
  group_by(TRT) %>% 
  summarize(
    lay = mean(Lying),
    laysd = sd(Lying),
    stand = mean(Standing),
    standsd = sd(Standing),
    steps = mean(Steps), 
    lb = mean(LB),
    mi = mean(MI)
  )


hour %>% 
  filter(hour >= -24 & hour <= 50) %>% 
  group_by(TRT, timecat) %>% 
  summarize(
    lay = mean(Lying),
    laysd = sd(Lying),
    stand = mean(Standing),
    standsd = sd(Standing),
    steps = mean(Steps), 
    lb = mean(LB),
    mi = mean(MI)
  )



hour |> 
  ggplot(aes (x = Lying))+
  geom_histogram()

hour |> 
  ggplot(aes (x = Standing))+
  geom_histogram()

hour |> 
  ggplot(aes (x = Steps))+
  geom_histogram()

hour |> 
  ggplot(aes (x = LB))+
  geom_histogram()



hourcut <-
  hour %>% 
  filter(hour >= -24 & hour <= 50)
write.csv(x = hourcut, file = "data/hourdatachecks.csv")
```

#### Plots by Time Category

```{r}

ggplot(hour, aes(x = TRT, y = Lying, color = TRT)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(vars(timecat)) +
  geom_jitter() +
    theme_classic()

hour$Lying_hr <- as.numeric(hour$Lying, units = "secs")
lm_lay <-lm(Lying_hr ~TRT*timecat, data=hour)
summary(lm_lay)
emmeans(lm_lay, ~TRT|timecat)
#plot(lm_lay)


ggplot(hour, aes(x = TRT, y = Standing, color = TRT)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(vars(timecat)) +
  geom_jitter() +
    theme_classic()

hour$stand <- as.numeric(hour$Standing, units = "secs")
lm_s <-lm(stand ~TRT*timecat, data=hour)
summary(lm_s)
emmeans(lm_s, ~TRT|timecat)
#plot(lm_s)


ggplot(hour, aes(x = TRT, y = Steps, color = TRT)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(vars(timecat)) +
  geom_jitter() +
    theme_classic()


lm_st <-lm(Steps ~TRT*timecat, data=hour)
summary(lm_st)
emmeans(lm_st, ~TRT|timecat)
#plot(lm_s)



ggplot(hour, aes(x = TRT, y = LB, color = TRT)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(vars(timecat)) +
  geom_jitter() +
    theme_classic()

lm_lb <-lm(LB ~TRT*timecat, data=hour)
summary(lm_lb)
emmeans(lm_lb, ~TRT|timecat)
#plot(lm_s)


ggplot(hour, aes(x = TRT, y = MI, color = TRT)) +
  geom_boxplot(outlier.shape = NA) +
  facet_wrap(vars(timecat)) +
  geom_jitter() +
    theme_classic()


lm_mi <-lm(MI ~TRT*timecat, data=hour)
summary(lm_mi)
emmeans(lm_mi, ~TRT|timecat)
#plot(lm_s)



```

#### Plot to sus out 3.5sf

```{r}
hour %>% 
  filter(hour >= 28 & hour <= 50) %>% 
  filter(timecat == "post") %>% 
  filter(TRT == "DF3.5") %>% 
  ggplot(aes(x=hour, y=Lying, color = factor(Cow), group = Cow))+
         geom_line (aes(fill = Cow), size = 1, alpha = 0.1)+
         geom_point()+ 
         theme_minimal()


hour %>% 
  filter(hour >= 28 & hour <= 50) %>% 
  filter(timecat == "post") %>% 
  filter(TRT == "DF3.0") %>% 
  ggplot(aes(x=hour, y=Lying, color = factor(Cow), group = Cow))+
         geom_line (aes(fill = Cow), size = 1, alpha = 0.1)+
         geom_point()+ 
         theme_minimal()


hour %>% 
  filter(hour >= 28 & hour <= 50) %>% 
  filter(timecat == "post") %>% 
  filter(TRT == "DF4.5") %>% 
  ggplot(aes(x=hour, y=Lying, color = factor(Cow), group = Cow))+
         geom_line (aes(fill = Cow), size = 1, alpha = 0.1)+
         geom_point()+ 
         theme_minimal()



#From these graphs it looks like the 3.5sd group had their icequbes removed as they came off the truck and/or soon after they arrived. There is enough variation in the other calves that it looks OK. 

#How do I sus this out further? Sum for each calf? 

hour %>% 
   filter(hour >= 29 & hour <= 50) %>%
  filter(timecat == "post") %>% 
  filter(TRT == "DF3.5") %>% 
  group_by(Cow) %>% 
  summarize(
    lay = sum(Lying), 
    lay1 = sum(Lying)/22
  )
  
#Then, if the summarized is 60 we can assume that the data is crap? 


```

## Hour

### Overall + By TRT

#### Laying

```{r}
#| warning: false
#| echo: false


laying <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying |> 
ggplot(aes(x = hoursfrom, y = lyingm)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



laying2 <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying2 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))


laying3 <- merged_data |> 
  filter(hoursfrom >= -24 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, Section) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, Section) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying3 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=Section)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))


#for checks to make sure categories are correct: 

laying2 <- merged_data |> 
  filter(hoursfrom >= 20 & hoursfrom <= 30) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying2 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(20, 30), breaks = seq(20, 30, by = 1))



laying2 <- merged_data |> 
  filter(hoursfrom >= -5 & hoursfrom <= 5) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying2 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-5, 5), breaks = seq(-5, 5, by = 1))






```

#### Standing

```{r}
#| warning: false
#| echo: false

standing <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Standing Time` = sum(`Standing Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    `Standing Time` = mean(`Standing Time`, na.rm = TRUE)) |> 
  mutate(
    standm = `Standing Time` / 60) |> 
  ungroup()


standing |> 
ggplot(aes(x = hoursfrom, y = standm)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Standing Time in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Standing Time (min)") +
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 6))



standing2 <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Standing Time` = sum(`Standing Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Standing Time` = mean(`Standing Time`, na.rm = TRUE)) |> 
  mutate(
    standm = `Standing Time` / 60) |> 
  ungroup()


standing2 |> 
ggplot(aes(x = hoursfrom, y = standm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Standing Time in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Standing Time (min)") +
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 6))




```

#### Steps

```{r}
#| warning: false
#| echo: false

stepgrp <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Steps` = sum(`Steps`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    steps = mean(`Steps`, na.rm = TRUE)) |> 
  ungroup()


stepgrp |> 
ggplot(aes(x = hoursfrom, y = steps)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Steps in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Steps(n)") +
    scale_y_continuous(limits = c(0, 200), breaks = seq(0, 200, by = 50))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



stepgrp <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Steps` = sum(`Steps`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    steps = mean(`Steps`, na.rm = TRUE)) |> 
  ungroup()


stepgrp |> 
ggplot(aes(x = hoursfrom, y = steps, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Steps in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Steps(n)") +
    scale_y_continuous(limits = c(0, 200), breaks = seq(0, 200, by = 50))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



```

#### Transitions

```{r}
#| warning: false
#| echo: false

lbgrp <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Transitions` = sum(`Transitions`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    lb = mean(`Transitions`, na.rm = TRUE)) |> 
  ungroup()


lbgrp |> 
ggplot(aes(x = hoursfrom, y = lb)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Transitions (LB) in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Transitions(n)") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 2))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



stepgrp2 <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Transitions` = sum(`Transitions`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    lb = mean(`Transitions`, na.rm = TRUE)) |> 
  ungroup()


stepgrp2 |> 
ggplot(aes(x = hoursfrom, y = lb, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Transitions in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Transitions(n)") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 2))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))
```

#### Motion Index

```{r}
#| warning: false
#| echo: false

migrp <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Motion Index` = sum(`Motion Index`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    mi = mean(`Motion Index`, na.rm = TRUE)) |> 
  ungroup()


migrp |> 
ggplot(aes(x = hoursfrom, y = mi)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Motion Index in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "MI") +
    scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 250))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



migrp2 <- merged_data |> 
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Motion Index` = sum(`Motion Index`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    mi = mean(`Motion Index`, na.rm = TRUE)) |> 
  ungroup()


migrp2 |> 
ggplot(aes(x = hoursfrom, y = mi, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Motion Index the 48hrs around transportation",
    x = "Hours from Transport",
    y = "MI") +
    scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 250))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 10))


#data checks, when to parse the data
migrp2 <- merged_data |> 
  filter(hoursfrom >= 25 & hoursfrom <= 30) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Motion Index` = sum(`Motion Index`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    mi = mean(`Motion Index`, na.rm = TRUE)) |> 
  ungroup()


migrp2 |> 
ggplot(aes(x = hoursfrom, y = mi, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Motion Index the 48hrs around transportation",
    x = "Hours from Transport",
    y = "MI") +
    scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 250))+
    scale_x_continuous(limits = c(25, 30), breaks = seq(25, 30, by = 1))




```

## Hour - One Load

### Overall + By TRT

#### Laying

```{r}
#| warning: false
#| echo: false


laying <- merged_data |> 
  filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()



laying |> 
ggplot(aes(x = hoursfrom, y = lyingm)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



laying2 <- merged_data |> 
  filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying2 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))


laying3 <- merged_data |> 
  filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, Section) |>  
  summarize(
    `Lying Time` = sum(`Lying Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, Section) |>  
  summarize(
    `Lying Time` = mean(`Lying Time`, na.rm = TRUE)) |> 
  mutate(
    lyingm = `Lying Time` / 60) |> 
  ungroup()


laying3 |> 
ggplot(aes(x = hoursfrom, y = lyingm, color=Section)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Lying Time in the 48hrs around long haul transport",
    x = "Hours from Trip Start",
    y = "Lying Time (min)")+
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))


```

#### Standing

```{r}
#| warning: false
#| echo: false

standing <- merged_data |> 
    filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Standing Time` = sum(`Standing Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    `Standing Time` = mean(`Standing Time`, na.rm = TRUE)) |> 
  mutate(
    standm = `Standing Time` / 60) |> 
  ungroup()


standing |> 
ggplot(aes(x = hoursfrom, y = standm)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Standing Time in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Standing Time (min)") +
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



standing2 <- merged_data |> 
    filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Standing Time` = sum(`Standing Time`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    `Standing Time` = mean(`Standing Time`, na.rm = TRUE)) |> 
  mutate(
    standm = `Standing Time` / 60) |> 
  ungroup()


standing2 |> 
ggplot(aes(x = hoursfrom, y = standm, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Standing Time in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Standing Time (min)") +
    scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 5))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 6))




```

#### Steps

```{r}
#| warning: false
#| echo: false

stepgrp <- merged_data |> 
    filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Steps` = sum(`Steps`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    steps = mean(`Steps`, na.rm = TRUE)) |> 
  ungroup()


stepgrp |> 
ggplot(aes(x = hoursfrom, y = steps)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Steps in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Steps(n)") +
    scale_y_continuous(limits = c(0, 200), breaks = seq(0, 200, by = 50))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



stepgrp <- merged_data |> 
    filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Steps` = sum(`Steps`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    steps = mean(`Steps`, na.rm = TRUE)) |> 
  ungroup()


stepgrp |> 
ggplot(aes(x = hoursfrom, y = steps, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Steps in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Steps(n)") +
    scale_y_continuous(limits = c(0, 200), breaks = seq(0, 200, by = 50))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



```

#### Transitions

```{r}
#| warning: false
#| echo: false

lbgrp <- merged_data |> 
     filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Transitions` = sum(`Transitions`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    lb = mean(`Transitions`, na.rm = TRUE)) |> 
  ungroup()


lbgrp |> 
ggplot(aes(x = hoursfrom, y = lb)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Transitions (LB) in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Transitions(n)") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 2))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



stepgrp2 <- merged_data |> 
     filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Transitions` = sum(`Transitions`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    lb = mean(`Transitions`, na.rm = TRUE)) |> 
  ungroup()


stepgrp2 |> 
ggplot(aes(x = hoursfrom, y = lb, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Transitions in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Transitions(n)") +
    scale_y_continuous(limits = c(0, 8), breaks = seq(0, 8, by = 2))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))
```

#### Motion Index

```{r}
#| warning: false
#| echo: false

migrp <- merged_data |> 
     filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom) |>  
  summarize(
    `Motion Index` = sum(`Motion Index`, na.rm = TRUE)) |> 
  group_by(hoursfrom) |>  
  summarize(
    mi = mean(`Motion Index`, na.rm = TRUE)) |> 
  ungroup()


migrp |> 
ggplot(aes(x = hoursfrom, y = mi)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Motion Index in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "MI") +
    scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 250))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))



migrp2 <- merged_data |> 
     filter(OneLoad == 1)|>
  filter(hoursfrom >= -16 & hoursfrom <= 50) |> 
  group_by(Cow, hoursfrom, TRT) |>  
  summarize(
    `Motion Index` = sum(`Motion Index`, na.rm = TRUE)) |> 
  group_by(hoursfrom, TRT) |>  
  summarize(
    mi = mean(`Motion Index`, na.rm = TRUE)) |> 
  ungroup()


migrp2 |> 
ggplot(aes(x = hoursfrom, y = mi, color=TRT)) +
  theme_classic() +
  geom_point() +  
  geom_line() +   
  labs(
    title = "Transitions in the 48hrs around transportation",
    x = "Hours from Transport",
    y = "Transitions(n)") +
    scale_y_continuous(limits = c(0, 1000), breaks = seq(0, 1000, by = 250))+
    scale_x_continuous(limits = c(-16, 50), breaks = seq(-16, 50, by = 8))
```
